"""
add_negotiation_tables

Hand-written migration template to add negotiation session and turn tables.
This file mirrors what `alembic revision --autogenerate -m "add_negotiation_tables"`
would produce. Do not run automatically; integrate with your Alembic setup first.
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "20251029_add_negotiation_tables"
down_revision = None  # TODO: set to your latest existing revision id
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "negotiation_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("property_id", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.String(length=50), nullable=True),
        sa.Column("user_role", sa.Enum("BUYER", "SELLER", name="userrole"), nullable=False),
        sa.Column("initial_asking_price", sa.Float(), nullable=False),
        sa.Column("target_price", sa.Float(), nullable=False),
        sa.Column("reservation_price", sa.Float(), nullable=False),
        sa.Column("current_offer", sa.Float(), nullable=True),
        sa.Column("round_number", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "ACCEPTED", "REJECTED", "ABANDONED", name="negotiationstatus"),
            nullable=False,
            server_default=sa.text("'ACTIVE'"),
        ),
        sa.Column("valuation_data", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_negotiation_sessions_session_id"),
        "negotiation_sessions",
        ["session_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_negotiation_sessions_property_id"),
        "negotiation_sessions",
        ["property_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_negotiation_sessions_user_id"),
        "negotiation_sessions",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_negotiation_sessions_status_created_at",
        "negotiation_sessions",
        ["status", "created_at"],
        unique=False,
    )

    op.create_table(
        "negotiation_turns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("turn_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("turn_number", sa.Integer(), nullable=False),
        sa.Column("actor", sa.Enum("USER", "AGENT", name="turnactor"), nullable=False),
        sa.Column("offer_amount", sa.Float(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["negotiation_sessions.session_id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_negotiation_turns_turn_id"),
        "negotiation_turns",
        ["turn_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_negotiation_turns_session_id"),
        "negotiation_turns",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        "ix_negotiation_turns_session_id_turn_number",
        "negotiation_turns",
        ["session_id", "turn_number"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_negotiation_turns_session_id_turn_number", table_name="negotiation_turns")
    op.drop_index(op.f("ix_negotiation_turns_session_id"), table_name="negotiation_turns")
    op.drop_index(op.f("ix_negotiation_turns_turn_id"), table_name="negotiation_turns")
    op.drop_table("negotiation_turns")

    op.drop_index("ix_negotiation_sessions_status_created_at", table_name="negotiation_sessions")
    op.drop_index(op.f("ix_negotiation_sessions_user_id"), table_name="negotiation_sessions")
    op.drop_index(op.f("ix_negotiation_sessions_property_id"), table_name="negotiation_sessions")
    op.drop_index(op.f("ix_negotiation_sessions_session_id"), table_name="negotiation_sessions")
    op.drop_table("negotiation_sessions")
    # ### end Alembic commands ###
